export const URLS = {
    login: "/login",
    register: "/register",

    home: "/",
    dashboard: "/dashboard",
    transactions: "/transactions",
    transfer: "/transfer",
    addMoney: "/add-money",
    requestDebin: "/request-debin",
    linkCard: "/link-card",
}

export const TEXT = {
    common: {
        appName: "BilleteraSeca",
        loading: "Cargando...",
        backToDashboard: "Volver al dashboard",
        seeAll: "Ver todo",
        currentBalance: "Saldo actual",
        availableBalance: "Saldo disponible",
        yourCurrentBalance: "Tu saldo actual en BilleteraSeca",
        seeTransactions: "Ver movimientos",
        errorOccurred: "Ha ocurrido un error",
        tryAgain: "Inténtalo de nuevo",
    },

    navbar: {
        home: "Inicio",
        dashboard: "Dashboard",
        transactions: "Transacciones",
        transfer: "Transferir",
        features: "Características",
        pricing: "Precios",
        login: "Iniciar sesión",
        register: "Registrarse",
        logout: "Salir",
    },

    home: {
        title: "Tu dinero, simplificado",
        subtitle: "Una billetera electrónica segura y fácil de usar para todas tus transacciones diarias.",
        createAccount: "Crear cuenta",
        login: "Iniciar sesión",
        accountManagement: {
            title: "Gestión de cuenta",
            description: "Administra tu dinero de forma sencilla",
            content: "Crea tu cuenta virtual, consulta tu saldo y gestiona tus finanzas desde cualquier dispositivo.",
            cta: "Comenzar",
        },
        p2pTransfers: {
            title: "Transferencias P2P",
            description: "Envía dinero al instante",
            content: "Transfiere dinero a otros usuarios mediante email o ID único de forma rápida y segura.",
            cta: "Descubrir",
        },
        bankIntegration: {
            title: "Integración bancaria",
            description: "Conecta tus cuentas externas",
            content: "Carga saldo desde tus cuentas bancarias o tarjetas y solicita débitos inmediatos (DEBIN).",
            cta: "Explorar",
        },
    },

    auth: {
        register: {
            title: "Crear cuenta",
            description: "Ingresa tus datos para crear una cuenta en BilleteraSeca",
            email: "Correo electrónico",
            password: "Contraseña",
            confirmPassword: "Confirmar contraseña",
            button: "Crear cuenta",
            buttonLoading: "Creando cuenta...",
            alreadyHaveAccount: "¿Ya tienes una cuenta?",
            loginLink: "Iniciar sesión",
            success: "Cuenta creada",
            successMessage: "Tu cuenta ha sido creada exitosamente",
            errorPasswordMatch: "Las contraseñas no coinciden",
            errorCreation: "No se pudo crear la cuenta. Inténtalo de nuevo.",
        },
        login: {
            title: "Iniciar sesión",
            description: "Ingresa tus credenciales para acceder a tu cuenta",
            email: "Correo electrónico",
            password: "Contraseña",
            forgotPassword: "¿Olvidaste tu contraseña?",
            button: "Iniciar sesión",
            buttonLoading: "Iniciando sesión...",
            noAccount: "¿No tienes una cuenta?",
            registerLink: "Crear cuenta",
            success: "Inicio de sesión exitoso",
            successMessage: "Has iniciado sesión correctamente",
            errorCredentials: "Credenciales incorrectas. Inténtalo de nuevo.",
        },
    },

    dashboard: {
        title: "Dashboard",
        balance: "Saldo disponible",
        balanceDescription: "Tu saldo actual en BilleteraSeca",
        quickActions: "Acciones rápidas",
        quickActionsDescription: "Operaciones frecuentes",
        actions: {
            transfer: "Transferir",
            add: "Agregar",
            debin: "DEBIN",
            link: "Vincular",
        },
        recentTransactions: "Transacciones recientes",
        recentTransactionsDescription: "Tus últimas operaciones",
        tabs: {
            recent: "Recientes",
            income: "Ingresos",
            expenses: "Gastos",
        },
        noTransactions: "No hay transacciones recientes",
        noIncome: "No hay ingresos recientes",
        noExpenses: "No hay gastos recientes",
        dropdownOptions: {
            viewDetails: "Ver detalles",
            hideBalance: "Ocultar saldo",
        },
    },

    transactions: {
        title: "Historial de transacciones",
        subtitle: "Visualiza y filtra todas tus operaciones",
        searchPlaceholder: "Buscar transacciones...",
        filterByType: "Filtrar por tipo",
        filterOptions: {
            all: "Todas",
            income: "Ingresos",
            expense: "Gastos",
            transfer: "Transferencias",
        },
        transactionsFound: "transacciones encontradas",
        noTransactionsFound: "No se encontraron transacciones",
        details: {
            to: "Para",
            from: "De",
        },
    },

    transfer: {
        title: "Transferir dinero",
        subtitle: "Envía dinero a otros usuarios de BilleteraSeca",
        sendMoney: "Enviar dinero",
        sendMoneyDescription: "Transfiere fondos a otro usuario",
        tabs: {
            email: "Email",
            id: "ID",
        },
        form: {
            recipientEmail: "Email del destinatario",
            recipientId: "ID del destinatario",
            amount: "Monto a transferir",
            description: "Descripción (opcional)",
            descriptionPlaceholder: "Motivo de la transferencia",
            button: "Enviar dinero",
            buttonLoading: "Enviando...",
        },
        success: "Transferencia exitosa",
        successMessage: "Has enviado {amount} a {recipient}",
        errors: {
            invalidAmount: "Por favor ingresa un monto válido",
            insufficientFunds: "No tienes suficiente saldo para realizar esta transferencia",
            noRecipient: "Por favor ingresa un destinatario",
            transferFailed: "No se pudo realizar la transferencia. Inténtalo de nuevo.",
        },
    },

    addMoney: {
        title: "Agregar dinero",
        subtitle: "Carga saldo a tu cuenta de BilleteraSeca",
        addFunds: "Agregar fondos",
        addFundsDescription: "Selecciona un método de carga",
        tabs: {
            card: "Tarjeta",
            bank: "Banco",
        },
        form: {
            cardNumber: "Número de tarjeta",
            expiryDate: "Fecha de expiración",
            cvv: "CVV",
            amount: "Monto a cargar",
            bankName: "Banco",
            accountNumber: "Número de cuenta",
            buttonCard: "Cargar dinero",
            buttonBank: "Transferir desde banco",
            buttonLoading: "Procesando...",
        },
        success: "Dinero agregado",
        successMessage: "Has agregado {amount} a tu cuenta",
        error: "No se pudo agregar dinero. Inténtalo de nuevo.",
    },

    requestDebin: {
        title: "Solicitar DEBIN",
        subtitle: "Solicita un débito inmediato desde tu cuenta bancaria",
        requestDebin: "Solicitar DEBIN",
        requestDebinDescription: "Completa los datos para solicitar un débito inmediato",
        form: {
            bankName: "Banco",
            accountNumber: "Número de cuenta",
            amount: "Monto a solicitar",
            button: "Solicitar DEBIN",
            buttonLoading: "Solicitando...",
        },
        success: "DEBIN solicitado",
        successMessage: "Has solicitado un DEBIN por {amount}",
        error: "No se pudo solicitar el DEBIN. Inténtalo de nuevo.",
    },

    linkCard: {
        title: "Vincular tarjeta",
        subtitle: "Agrega una tarjeta para cargar saldo fácilmente",
        newCard: "Nueva tarjeta",
        newCardDescription: "Ingresa los datos de tu tarjeta",
        form: {
            cardNumber: "Número de tarjeta",
            cardHolder: "Titular de la tarjeta",
            cardHolderPlaceholder: "Nombre como aparece en la tarjeta",
            expiryDate: "Fecha de expiración",
            cvv: "CVV",
            button: "Vincular tarjeta",
            buttonLoading: "Vinculando...",
        },
        success: "Tarjeta vinculada",
        successMessage: "Tu tarjeta ha sido vinculada exitosamente",
        error: "No se pudo vincular la tarjeta. Inténtalo de nuevo.",
    },
}
